_wandb:
    value:
        cli_version: 0.21.0
        e:
            yk9z26ahsqmphipdshxbjx5jcdhkhkrx:
                apple:
                    ecpuCores: 4
                    gpuCores: 30
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "2147483648"
                codePath: msldm_voice2instrumental/train.py
                codePathLocal: msldm_voice2instrumental/train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1995218165760"
                        used: "1182652772352"
                email: joaopaesteves99@gmail.com
                executable: /Users/joaoesteves/mli/SingwithML/venv/bin/python
                git:
                    commit: 603eb1097d7588d302db0e1798bea0947a3ada2b
                    remote: git@github.com:jpe17/SingwithML.git
                host: Joaos-MacBook-Pro.local
                memory:
                    total: "34359738368"
                os: macOS-15.5-arm64-arm-64bit
                program: msldm_voice2instrumental/train.py
                python: CPython 3.8.18
                root: /Users/joaoesteves/mli/SingwithML
                startedAt: "2025-07-09T22:04:54.012Z"
                writerId: yk9z26ahsqmphipdshxbjx5jcdhkhkrx
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.8.18
            "5": 0.21.0
            "12": 0.21.0
            "13": darwin-arm64
batch_size:
    value: 16
beta_end:
    value: 0.02
beta_start:
    value: 0.0001
diffusion_steps:
    value: 1000
gradient_clip:
    value: 1
hop_length:
    value: 512
inference_steps:
    value: 50
learning_rate:
    value: 0.0001
n_fft:
    value: 2048
num_epochs:
    value: 100
sample_rate:
    value: 44100
segment_length:
    value: 131072
test_split:
    value: 0.1
train_split:
    value: 0.8
unet_attention_levels:
    value:
        - 1
        - 2
        - 3
unet_channels:
    value:
        - 128
        - 256
        - 512
        - 1024
vae_channels:
    value:
        - 64
        - 128
        - 256
        - 512
vae_latent_dim:
    value: 80
vae_strides:
    value:
        - 2
        - 2
        - 2
        - 2
val_split:
    value: 0.1
win_length:
    value: 2048
